# Generated by Django 5.0.6 on 2024-07-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tages'},
        ),
        migrations.AddField(
            model_name='tags',
            name='tags',
            field=models.CharField(default='# product', max_length=100),
        ),
    ]
