# Generated by Django 5.0.6 on 2024-08-06 01:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_tags_alter_productimages_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='this is the product.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='i am Amazing vendor.', null=True),
        ),
    ]
