# Generated by Django 5.0.6 on 2024-08-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cartitem_cart_cartitem_user_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
