# Generated by Django 5.0.6 on 2024-08-29 10:00

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, default='P_IDxxxxx', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='BaylingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghij12345', length=10, max_length=15, prefix='', unique=True)),
                ('your_name', models.CharField(default='your name', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('division', models.CharField(choices=[('dhaka', 'DHAKA'), ('chattogram', 'CHATTOGRAM'), ('rajshahi', 'RAJSHAHI'), ('khulna', 'KHULNA'), ('barishal', 'BARISHAL'), ('sylhet', 'SYLHET'), ('rangpur', 'RANGPUR'), ('mymensingh', 'MYMENSINGH')], default='dhaka', max_length=25)),
                ('district', models.CharField(choices=[('dhaka', 'DHAKA'), ('faridpur', 'FARIDPUR'), ('gazipur', 'GAZIPUR'), ('gopalganj', 'GOPALGANJ'), ('kishoreganj', 'KISHOREGANJ'), ('madaripur', 'MADARIPUR'), ('manikganj', 'MANIKGANJ'), ('munshiganj', 'MUNSHIGANJ'), ('narayanganj', 'NARAYANGANJ'), ('narsingdi', 'NARSINGDI'), ('rajbari', 'RAJBARI'), ('shariatpur', 'SHARIATPUR'), ('tangail', 'TANGAIL'), ('bagerhat', 'BAGERHAT'), ('chuadanga', 'CHUADANGA'), ('jashore', 'JASHORE'), ('jhenaidah', 'JHENAIDAH'), ('khulna', 'KHULNA'), ('kushtia', 'KUSHTIA'), ('magura', 'MAGURA'), ('meherpur', 'MEHERPUR'), ('narail', 'NARAIL'), ('satkhira', 'SATKHIRA'), ('bogura', 'BOGURA'), ('joypurhat', 'JOYPURHAT'), ('naogaon', 'NAOGAON'), ('natore', 'NATORE'), ('chapainawabganj', 'CHAPAINAWABGANJ'), ('pabna', 'PABNA'), ('rajshahi', 'RAJSHAHI'), ('sirajganj', 'SIRAJGANJ'), ('dinajpur', 'DINAJPUR'), ('gaibandha', 'GAIBANDHA'), ('kurigram', 'KURIGRAM'), ('lalmonirhat', 'LALMONIRHAT'), ('nilphamari', 'NILPHAMARI'), ('panchagarh', 'PANCHAGARH'), ('rangpur', 'RANGPUR'), ('thakurgaon', 'THAKURGAON'), ('barguna', 'BARGUNA'), ('barishal', 'BARISHAL'), ('bhola', 'BHOLA'), ('jhalokathi', 'JHALOKATHI'), ('patuakhali', 'PATUAKHALI'), ('pirojpur', 'PIROJPUR'), ('bandarban', 'BANDARBAN'), ('brahmanbaria', 'BRAHMANBARIA'), ('chandpur', 'CHANDPUR'), ('chattogram', 'CHATTOGRAM'), ('cumilla', 'CUMILLA'), ('coxsbazar', 'COXSBAZAR'), ('feni', 'FENI'), ('khagrachari', 'KHAGRACHARI'), ('lakshmipur', 'LAKSHMIPUR'), ('noakhali', 'NOAKHALI'), ('rangamati', 'RANGAMATI'), ('habiganj', 'HABIGANJ'), ('moulvibazar', 'MOULVIBAZAR'), ('sunamganj', 'SUNAMGANJ'), ('sylhet', 'SYLHET'), ('mymensingh', 'MYMENSINGH'), ('netrokona', 'NETROKONA'), ('sherpur', 'SHERPUR'), ('jamalpur', 'JAMALPUR')], default='dhaka', max_length=30)),
                ('home_address', models.CharField(default='N/A', max_length=300)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
    ]
