# Generated by Django 5.0.6 on 2024-08-31 02:45

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_order_payment_id_baylingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baylingaddress',
            name='district',
            field=models.CharField(choices=[('bagerhat', 'BAGERHAT'), ('bandarban', 'BANDARBAN'), ('barguna', 'BARGUNA'), ('barishal', 'BARISHAL'), ('bhola', 'BHOLA'), ('bogura', 'BOGURA'), ('brahmanbaria', 'BRAHMANBARIA'), ('chapainawabganj', 'CHAPAINAWABGANJ'), ('chandpur', 'CHANDPUR'), ('chattogram', 'CHATTOGRAM'), ('chuadanga', 'CHUADANGA'), ('cumilla', 'CUMILLA'), ('coxsbazar', 'COXSBAZAR'), ('dinajpur', 'DINAJPUR'), ('dhaka', 'DHAKA'), ('faridpur', 'FARIDPUR'), ('feni', 'FENI'), ('gaibandha', 'GAIBANDHA'), ('gazipur', 'GAZIPUR'), ('gopalganj', 'GOPALGANJ'), ('habiganj', 'HABIGANJ'), ('jamalpur', 'JAMALPUR'), ('jashore', 'JASHORE'), ('jhalokathi', 'JHALOKATHI'), ('jhenaidah', 'JHENAIDAH'), ('joypurhat', 'JOYPURHAT'), ('khagrachari', 'KHAGRACHARI'), ('kishoreganj', 'KISHOREGANJ'), ('khulna', 'KHULNA'), ('kurigram', 'KURIGRAM'), ('kushtia', 'KUSHTIA'), ('lakshmipur', 'LAKSHMIPUR'), ('lalmonirhat', 'LALMONIRHAT'), ('madaripur', 'MADARIPUR'), ('magura', 'MAGURA'), ('manikganj', 'MANIKGANJ'), ('meherpur', 'MEHERPUR'), ('moulvibazar', 'MOULVIBAZAR'), ('munshiganj', 'MUNSHIGANJ'), ('mymensingh', 'MYMENSINGH'), ('narail', 'NARAIL'), ('narayanganj', 'NARAYANGANJ'), ('narsingdi', 'NARSINGDI'), ('natore', 'NATORE'), ('netrokona', 'NETROKONA'), ('nilphamari', 'NILPHAMARI'), ('noakhali', 'NOAKHALI'), ('pabna', 'PABNA'), ('panchagarh', 'PANCHAGARH'), ('patuakhali', 'PATUAKHALI'), ('pirojpur', 'PIROJPUR'), ('rajbari', 'RAJBARI'), ('rajshahi', 'RAJSHAHI'), ('rangamati', 'RANGAMATI'), ('rangpur', 'RANGPUR'), ('satkhira', 'SATKHIRA'), ('shariatpur', 'SHARIATPUR'), ('sherpur', 'SHERPUR'), ('sirajganj', 'SIRAJGANJ'), ('sunamganj', 'SUNAMGANJ'), ('sylhet', 'SYLHET'), ('tangail', 'TANGAIL'), ('thakurgaon', 'THAKURGAON')], default='dhaka', max_length=30),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=15, prefix='', unique=True)),
                ('your_name', models.CharField(default='your name', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('transaction', models.CharField(default='txid_xxx', max_length=100)),
                ('payment_method', models.CharField(blank=True, default=None, max_length=20)),
                ('tr_date', models.DateField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
    ]
