# Generated by Django 5.0.6 on 2024-08-31 04:20

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_baylingaddress_district_paymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='pr_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='accdefghij12345', length=10, max_length=15, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='transaction',
            field=models.CharField(blank=True, default='txid_xxx', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='your_name',
            field=models.CharField(blank=True, default='your name', max_length=30),
        ),
    ]
