# Generated by Django 5.0.6 on 2024-09-03 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(default='default_room', max_length=255),
        ),
        migrations.AddField(
            model_name='chat',
            name='cid',
            field=models.CharField(default='defult_cid_value', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
