# Generated by Django 5.0.6 on 2024-09-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0002_chat_chat_name_chat_cid_chat_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='cid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
